name: srw_app
channels:
  - conda-forge
  - ufs-community
dependencies:
  - pylint=2.17*
  - pytest=7.2*
  - uwtools=2.3*
  - esmpy=8.6.*
  - netcdf4=1.6.*
  - numpy=1.23.*
  - pandas=1.5.*
  - scipy=1.10.*
  - xarray=2022.11.*

