name: srw_graphics
channels:
  - conda-forge
dependencies:
  - python=3.9*
  - cartopy=0.18*
  - matplotlib=3.5*
  - pillow=9.2*
  - pygrib=2.1*
  - pylint=2.16*
  - pyproj=2.6*
  - pytest=7.1*
  - pyyaml=6.0*
  - scipy=1.9*
