metadata:
  description: |-
    This test is to ensure that the workflow running in community mode
    can successfully run the MET deterministic verification tasks but
    using staged observation and forecast files (i.e. with other tasks
    such as pre-processing, forecast, and post-processing deactivated).
user:
  RUN_ENVIR: community
  MACHINE: hera
  ACCOUNT: rtrr
workflow:
  PREDEF_GRID_NAME: RRFS_CONUS_25km
  DATE_FIRST_CYCL: '2019061500'
  DATE_LAST_CYCL: '2019061500'
  FCST_LEN_HRS: 6
  PREEXISTING_DIR_METHOD: rename
  COMPILER: intel
  EXPT_SUBDIR: MET_verification_only_vx
rocoto:
  tasks:
    taskgroups: '{{ ["parm/wflow/verify.yaml"]|include }}'
    task_get_obs_ccpa: null
    task_get_obs_mrms: null
    task_get_obs_ndas: null
    metatask_vx_ens_member:
      metatask_GridStat_MRMS_mem#mem#:
        task_run_MET_GridStat_vx_#VAR#_mem#mem#:
          dependency: null
      metatask_PointStat_mem#mem#:
        task_run_MET_PointStat_vx_#VAR#_mem#mem#:
          dependency: null
    metatask_GridStat_APCP_acc:
      metatask_vx_ens_member_acc:
        task_run_MET_PcpCombine_fcst_APCP#ACCUM_HR#h_mem#mem#:
          dependency: null
verification:
  VX_FCST_MODEL_NAME: FV3_GFS_v15p2_CONUS_25km
  VX_FCST_INPUT_DIR: '{{ platform.get("TEST_VX_FCST_INPUT_DIR") }}'
platform:
  BUILD_MOD_FN: build_hera_intel
