metadata:
  description: >-
    Sample config file for the work of importing RRFS_dev1 tasks
    to SRW
user:
  RUN_ENVIR: nco
  MACHINE: hera
  ACCOUNT: zrtrr
  SERVICE_ACCOUNT: zrtrr
platform:
  RESERVATION: ""
  SST_update_hour: 1
  GVF_update_hour: 4
  SNOWICE_update_hour: 0
  ARCHIVEDIR: "/1year/BMC/wrfruc/rrfs_dev1"
  NCARG_ROOT: "/apps/ncl/6.5.0-CentOS6.10_64bit_nodap_gnu447"
  NCL_HOME: "/home/rtrr/RRFS/graphics"
  NCL_REGION: "conus"
  DOMAIN_PREGEN_BASEDIR: "/scratch2/BMC/gsd-hpcs/Daniel.Abdi/rrfs_dev/ufs-srweather-app/regional_workflow/fix/lam"
  FIXgsi: "/scratch2/BMC/gsd-hpcs/Daniel.Abdi/rrfs_dev/ufs-srweather-app/regional_workflow/fix/gsi"
  FIXcrtm: "/scratch2/BMC/gsd-hpcs/Daniel.Abdi/rrfs_dev/ufs-srweather-app/regional_workflow/fix/crtm/CRTM_v2.3.0"
  FIXcrtmupp: "/scratch2/BMC/gsd-hpcs/Daniel.Abdi/rrfs_dev/ufs-srweather-app/regional_workflow/fix/crtm/CRTM_v2.4.0"
workflow:
  TAG: RRFS_CONUS_3km_
  USE_CRON_TO_RELAUNCH: false
  EXPT_SUBDIR: RRFS_CONUS_3km
  CCPP_PHYS_SUITE: FV3_HRRR
  PREDEF_GRID_NAME: RRFS_CONUS_3km
  DATE_FIRST_CYCL: '2021072400'
  DATE_LAST_CYCL: '2021073000'
  FCST_LEN_HRS: 3
  FCST_LEN_HRS_SPINUP: 1
  POSTPROC_LEN_HRS: 3
  POSTPROC_LONG_LEN_HRS: 12
  PREEXISTING_DIR_METHOD: rename
  DEBUG: true
  VERBOSE: true
  COMPILER: intel
  CYCL_HRS: [0, 12]
  CYCL_HRS_SPINSTART: [3, 15]
  CYCL_HRS_PRODSTART: [9, 21]
  FCST_LEN_HRS_CYCLES: []
  DA_CYCLE_INTERV: 1
  RESTART_INTERVAL: 1
  BOUNDARY_LEN_HRS: 18
  BOUNDARY_PROC_GROUP_NUM: 10
workflow_switches:
  RUN_TASK_MAKE_GRID: false
  RUN_TASK_MAKE_OROG: false
  RUN_TASK_MAKE_SFC_CLIMO: false
  RUN_TASK_PLOT_ALLVARS: false
  DO_DACYCLE: true
  DO_SURFACE_CYCLE: true
  DO_SPINUP: true
  DO_RETRO: true
  DO_NONVAR_CLDANAL: true
  DO_REFL2TTEN: false
  DO_SOIL_ADJUST: true
  DO_RADDA: false
  DO_BUFRSND: false
  DO_RRFS_DEV: true
  DO_POST_SPINUP: true
  DO_POST_PROD: true
cycledefs:
  CYCLEMONTH: "7"
  CYCLEDAY: "24-30"
  INITIAL_CYCLEDEF: '{{ [workflow.DATE_FIRST_CYCL[0:8], "0300 ", workflow.DATE_LAST_CYCL[0:8], "2300 12:00:00"]|join }}'
  BOUNDARY_CYCLEDEF: '{{ [workflow.DATE_FIRST_CYCL[0:8], "0000 ", workflow.DATE_LAST_CYCL[0:8], "2300 06:00:00"]|join }}'
  PROD_CYCLEDEF: '{{ [workflow.DATE_FIRST_CYCL[0:8], "0900 ", workflow.DATE_LAST_CYCL[0:8], "2300 01:00:00"]|join }}'
  ARCHIVE_CYCLEDEF: '{{ [workflow.DATE_FIRST_CYCL[0:8], "0700 ", workflow.DATE_LAST_CYCL[0:8], "2300 24:00:00"]|join }}'
  SPINUP_CYCLEDEF: '{{ ["00 03-08,15-20 ", cycledefs.CYCLEDAY, " ", cycledefs.CYCLEMONTH, " 2021 *"]|join }}'
gsi:
  HYBENSMEM_NMIN: 66
nco:
  NET: rrfs
  envir: para
  model_ver: v1.0
  RUN: RRFS_conus_3km
task_get_extrn_ics:
  EXTRN_MDL_NAME_ICS: FV3GFS
  FV3GFS_FILE_FMT_ICS: grib2
  EXTRN_MDL_FILES_ICS:
    - '{yy}{jjj}{hh}0000{fcst_hr:02d}'
  EXTRN_MDL_ICS_OFFSET_HRS: 3
  USE_USER_STAGED_EXTRN_FILES: true
  EXTRN_MDL_SOURCE_BASEDIR_ICS: "/scratch2/BMC/zrtrr/rli/data/gfs/0p25deg/grib2"
task_get_extrn_lbcs:
  EXTRN_MDL_NAME_LBCS: FV3GFS
  FV3GFS_FILE_FMT_LBCS: grib2
  EXTRN_MDL_FILES_LBCS:
    - '{yy}{jjj}{hh}0000{fcst_hr:02d}'
  LBC_SPEC_INTVL_HRS: 1
  EXTRN_MDL_LBCS_OFFSET_HRS: 6
  USE_USER_STAGED_EXTRN_FILES: true
  EXTRN_MDL_SOURCE_BASEDIR_LBCS: "/scratch2/BMC/zrtrr/rli/data/gfs/0p25deg/grib2"
task_make_ics:
  NNODES_MAKE_ICS: 3
  PPN_MAKE_ICS: 20
task_make_lbcs:
  NNODES_MAKE_LBCS: 3
  PPN_MAKE_LBCS: 20
  WTIME_MAKE_LBCS: 02:00:00
task_run_fcst:
  DT_ATMOS: 60
  WRITE_DOPOST: true
  QUILTING: true
  IO_LAYOUT_Y: 1
  WTIME_RUN_FCST: 02:45:00
  FH_DFI_RADAR: "0.0,0.25,0.5"
task_run_post:
  NNODES_RUN_POST: 1
  PPN_RUN_POST: 40
  USE_CUSTOM_POST_CONFIG_FILE: false
  POST_OUTPUT_DOMAIN_NAME: RRFS_CONUS_3km
  CUSTOM_POST_CONFIG_FP: '{{ [platform.FIXcrtmupp, "upp/postxconfig-NT-fv3lam.txt"]|path_join }}'
  CUSTOM_POST_PARAMS_FP: '{{ [platform.FIXcrtmupp, "upp/params_grib2_tbl_new"]|path_join }}'
  TESTBED_FIELDS_FN: "testbed_fields_bgdawp.txt"
  TESTBED_FIELDS_FN2: "testbed_fields_bgrd3d.txt"
task_run_anal:
  NCORES_RUN_ANAL: 240
  NCORES_RUN_OBSERVER: 80
task_run_ref2tten:
  PPN_RUN_REF2TTEN: 1
task_run_nonvarcldanl:
  PPN_RUN_NONVARCLDANL: '{{ task_run_fcst.IO_LAYOUT_Y }}'
task_plot_allvars:
  COMOUT_REF: ""
global:
  NUM_ENS_MEMBERS: 9
  HALO_BLEND: 20
  PRINT_DIFF_PGR: true
  ADDNL_OUTPUT_GRIDS: []
  TILE_LABELS: "full"
  TILE_SETS: "full"
  RADARREFL_TIMELEVEL: [0]
