metadata:
  description: config for SRW-AQM, AQM_NA_13km, warm-start
user:
  RUN_ENVIR: community
  MACHINE: hera
  ACCOUNT: naqfc 
platform:
  FIXaqm: /scratch1/NCEPDEV/nems/Brian.Curtis/fixaqm
workflow:
  USE_CRON_TO_RELAUNCH: true
  CRON_RELAUNCH_INTVL_MNTS: 3
  EXPT_SUBDIR: /scratch1/NCEPDEV/stmp2/Brian.Curtis/aqm_AQMNA13km_warmstart
  PREDEF_GRID_NAME: AQM_NA_13km
  CCPP_PHYS_SUITE: FV3_GFS_v16
  DATE_FIRST_CYCL: '2023080112'
  DATE_LAST_CYCL: '2023080212'
  INCR_CYCL_FREQ: 24
  FCST_LEN_HRS: 24
  PREEXISTING_DIR_METHOD: rename
  VERBOSE: true
  DEBUG: false
  COMPILER: intel
  DIAG_TABLE_TMPL_FN: diag_table_aqm.FV3_GFS_v16
  FIELD_TABLE_TMPL_FN: field_table_aqm.FV3_GFS_v16
  DO_REAL_TIME: false
  COLDSTART: false      # set to true for cold start
  WARMSTART_CYCLE_DIR: '/scratch1/NCEPDEV/nems/Brian.Curtis'
#  WARMSTART_CYCLE_DIR: '/scratch2/NAGAPE/epic/SRW-AQM_DATA/aqm_data/restart/2023111000' # for hera
#  WARMSTART_CYCLE_DIR: '/work/noaa/epic/SRW-AQM_DATA/aqm_data/restart/2023111000' # for orion/hercules
#  WARMSTART_CYCLE_DIR: '/glade/work/chanhooj/SRW-AQM_DATA/aqm_data/restart/2023111000' # for derecho
nco:
  envir_default: test_aqm_warmstart
  NET_default: aqm
  RUN_default: aqm
  MAILTO_default: brian.curtis@noaa.gov
rocoto:
  tasks:
#    taskgroups: '{{ ["parm/wflow/prep.yaml", "parm/wflow/aqm_prep.yaml", "parm/wflow/coldstart.yaml", "parm/wflow/post.yaml"]|include }}'
    taskgroups: '{{ ["parm/wflow/aqm_prep.yaml", "parm/wflow/coldstart.yaml", "parm/wflow/post.yaml"]|include }}'

#    task_aqm_ics_ext:    # uncomment this in case of COLDSTART: true
    metatask_run_ensemble:
      task_run_fcst_mem#mem#:
        walltime: 01:20:00
task_make_grid:
  GRID_DIR: /scratch2/NCEPDEV/naqfc/RRFS_CMAQ/DOMAIN_DATA/AQM_NA_13km
task_make_orog:
  OROG_DIR: /scratch2/NCEPDEV/naqfc/RRFS_CMAQ/DOMAIN_DATA/AQM_NA_13km
task_make_sfc_climo:
  SFC_CLIMO_DIR: /scratch2/NCEPDEV/naqfc/RRFS_CMAQ/DOMAIN_DATA/AQM_NA_13km
task_get_extrn_ics:
  EXTRN_MDL_NAME_ICS: FV3GFS
  FV3GFS_FILE_FMT_ICS: netcdf
  EXTRN_MDL_ICS_OFFSET_HRS: 0
task_get_extrn_lbcs:
  EXTRN_MDL_NAME_LBCS: FV3GFS
  LBC_SPEC_INTVL_HRS: 6
  FV3GFS_FILE_FMT_LBCS: netcdf
  EXTRN_MDL_LBCS_OFFSET_HRS: 0
task_run_fcst:
  DT_ATMOS: 180
  LAYOUT_X: 50
  LAYOUT_Y: 34
  BLOCKSIZE: 16
  RESTART_INTERVAL: 6 12 24
  QUILTING: true
  PRINT_ESMF: true
  DO_FCST_RESTART: true
task_run_post:
  POST_OUTPUT_DOMAIN_NAME: 793
  USE_CUSTOM_POST_CONFIG_FILE: false
global:
  DO_ENSEMBLE: false
  NUM_ENS_MEMBERS: 2
  HALO_BLEND: 0
cpl_aqm_parm:
  CPL_AQM: true
  DO_AQM_CHEM_LBCS: true
  DO_AQM_GEFS_LBCS: true
  DO_AQM_DUST: true
  DO_AQM_CANOPY: false
  DO_AQM_PRODUCT: true
  DO_AQM_SAVE_AIRNOW_HIST: false
  DO_AQM_SAVE_FIRE: false
  AQM_BIO_FILE: BEIS_RRFScmaq_C775.ncf
  AQM_DUST_FILE_PREFIX: FENGSHA_p8_10km_inputs
  AQM_DUST_FILE_SUFFIX: .nc  
  AQM_CANOPY_FILE_PREFIX: gfs.t12z.geo
  AQM_CANOPY_FILE_SUFFIX: .canopy_regrid.nc
  COMINfire_default: /scratch1/NCEPDEV/nems/Brian.Curtis/RAVE_fire
  #AQM_FIRE_FILE_PREFIX: Hourly_Emissions_regrid_NA_13km
  AQM_FIRE_FILE_PREFIX: Hourly_Emissions_13km
  AQM_FIRE_FILE_SUFFIX: _h72.nc
  AQM_RC_FIRE_FREQUENCY: hourly
  AQM_LBCS_FILES: am4_bndy.c793.2019<MM>.v1.nc
  COMINgefs_default: /scratch1/NCEPDEV/stmp4/Patrick.C.Campbell/GEFS_Aerosol
  AQM_GEFS_FILE_PREFIX: gfs
  AQM_GEFS_FILE_CYC: 00
  NEXUS_GRID_FN: grid_spec_793.nc
  NUM_SPLIT_NEXUS: 6

