name: Build SRW
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: [self-hosted, ncar]
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: |
             cd ufs-srweather-app
             ./manage_externals/checkout_externals
             ./devbuild.sh -p=cheyenne -c=intel
      - run: echo "🍏 This job's status is ${{ job.status }}."
