name: Doc Tests
on:
  push:
    branches:
      - develop
      - 'release/*'
  pull_request:
    branches:
      - develop
      - 'release/*'
  workflow_dispatch:
    branches:
      - 'feature/doc-actions'

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  doc_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build documentation
        run: .github/scripts/doc_build.sh
